### ISSUE TITLE
페이지네이션 기능중에 총 몇페이지인지 조회하는 기능이 필요 할 것으로 보입니다.

### ISSUE THREAD

**Issue by WachsenHaus** [dduckddack-coinTalk/news-server#1]
# 요청사항

<img src="https://user-images.githubusercontent.com/59411545/168341325-4c1786f9-a86a-4af7-9e72-b54233ebc73e.png" width="200" height="auto"/>

현재 올려주신 API명세서를 보아 서버에서 제공해주는 페이지가 총 몇 페이지인지 알 수가 없어 끝 데이터를 조회 할 수 없습니다.

ex) size를 5로 했을경우 서버에서 제공하는 totalPage50개이고,  250개의 뉴스가 있다.

클라이언트에서 최대 페이지갯수를 알 수 있는 메소드가 추가되면 좋겠습니다.

**Comment by HayanYoo** [comment]
추가하였습니다 👍
