### ISSUE TITLE
마지막 페이지의 경우 빈배열이 나옵니다.

### ISSUE THREAD

**Issue by WachsenHaus** [dduckddack-coinTalk/news-server#2]
https://cointalk.kro.kr:8080/news?page=76&size=6&keyword=

마지막페이지로 요청할 경우 빈배열이 나옵니다 확인 해주세용~

**Comment by HayanYoo** [comment]
확인했습니다~ 해당 부분 수정하였고, 페이지 인덱스를 0번부터 시작해주세용

**Comment by WachsenHaus** [comment]
네 잘 동작합니다. 감사합니다 ^_^
